### ISSUE TITLE
Tarea de Infrografia de Sistema Numericos

### ISSUE THREAD

**Issue by Erick-3as** [SistemasTecTlaxiaco/infografia-Erick-3as#3]
[Sistema Numéricos .pdf](https://github.com/SistemasTecTlaxiaco/infografia-Erick-3as/files/7125126/Sistema.Numericos.pdf)

**Comment by JulioCGz** [comment]
17 de calificación

**Comment by josealfredo79** [comment]
Espero que hayan evaluado de acuerdo a rúbrica. Bien hecho y revisado
